from collections import deque
q = deque(['name','age','DOB'])
print(q)
print("........................................................................................................................")
d = deque([1,2,3,4])
d.append(5)
print("after appending::",d)
d.appendleft(6)
print("after appendingleft::",d)
d.pop()
print("after deleting ::",d)
d.popleft()
print("after deleting left::",d)
print("........................................................................................................................")
de = deque([1,2,3,4,5])
print("the number first occured at a position::",de.index(4,2,5))
de.insert(4,3)
print(de)
print("the count of 3 in deque::",de.count(3))
de.remove(3)
print("the after deleting of deque::",de)
print("........................................................................................................................")
de = deque([1,2,3,4])
print(de)
de.extend([5,6,7,8])
print("after extend::",de)
de.extendleft([0,-1,-2,-3])
print("after extend left::",de)
de.reverse()
print("the deque after reversed::",de)
de.rotate(-3)
print("after rotate ::",de)